### ISSUE TITLE
REPORTERS: List of possible backends

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/progressr#19]
# Auditory

* [x] [beepr](https://cran.r-project.org/package=beepr): Easily Play Notification Sounds on any Platform
* [ ] [drumr](https://cran.r-project.org/package=drumr): Turn R into a Drum Machine. Uses **audio** package.
* [ ] [googleLanguageR](https://cran.r-project.org/package=googleLanguageR): Call Google's 'Natural Language' API, 'Cloud Translation' API, 'Cloud Speech' API and ['Cloud Text-to-Speech' API](https://cran.r-project.org/web/packages/googleLanguageR/vignettes/text-to-speech.html) [Issue #25]
   - Requires: Google Cloud Developers account
   - Pricing: [4*10^6 characters/month free, then 4 USD/10^6 characters](https://cloud.google.com/text-to-speech/pricing).  E.g. 4 million chars/month is ~5,500 chars/hour or 92 chars/min (24/7!)
* [ ] [music](https://cran.r-project.org/web/packages/music/index.html): Learn and Experiment with Music Theory. Uses **audio** package.
* [ ] [phonTools](https://cran.r-project.org/package=phonTools): Tools for Phonetic and Acoustic Analyses
* [ ] [seewave](https://cran.r-project.org/package=seewave): Sound Analysis and Synthesis. Uses **audio** package.
* [ ] [sonify](https://cran.r-project.org/package=sonify): Data Sonification - Turning Data into Sound. Uses **tuneR**  for audio playback
* [ ] [sound](https://cran.r-project.org/package=sound): A Sound Interface for R. "For playing sounds, a command line system tool for playing wav-files is required."
* [ ] [soundgen](https://cran.r-project.org/package=soundgen): Parametric Voice Synthesis  <== cool. Uses **tuneR**  for audio playback
* [ ] [tuneR](https://cran.r-project.org/package=tuneR): Analysis of Music and Speech
* [ ] macOS TTS, e.g. `system("say -v ...")`, cf. https://twitter.com/geographiliac/status/1390688275698966534
* [ ] Free-flying variometer (Feature Request https://github.com/HenrikBengtsson/progressr/issues/20)
* [ ]  "incremental tones for audio, similar to [JGauge Progress Bar](https://www.dlee.org/jgauge/)" (Feature Request https://github.com/HenrikBengtsson/progressr/issues/143)

# Email

* [ ] [apprise](https://github.com/caronc/apprise) Push Notifications that work with just about every platform! 
* [ ] [blastula](https://cran.r-project.org/package=blastula): Easily Send HTML Email Messages
* [ ] [blatr](https://cran.r-project.org/package=blatr): Send Emails Using 'Blat' for Windows
* [ ] [gmailr](https://cran.r-project.org/package=gmailr): Access the Gmail RESTful API
* [ ] [IMmailgun](https://cran.r-project.org/package=IMmailgun): Send Emails using 'Mailgun'
* [ ] [mail](https://cran.r-project.org/package=mail): Sending Email Notifications from R
* [ ] [mailR](https://cran.r-project.org/package=mailR): A Utility to Send Emails from R
* [ ] [sendmailR](https://cran.r-project.org/package=sendmailR): send email using R

# Notification frameworks

* [x] notifier: Cross Platform Desktop Notifications
* [ ] [notifyme](https://cran.r-project.org/package=notifyme): Send Alerts to your Cellphone and Phillips Hue Lights
* [ ] ~~[notifyR](https://cran.r-project.org/package=notifyR)~~: Send push notifications to your smartphone via pushover.net (ACCOUNT REQUIRED) [package archived on CRAN on 2022-05-09]
* [ ] [pushoverr](https://cran.r-project.org/package=pushoverr): Send Push Notifications using Pushover (ACCOUNT REQUIRED)
* [x] [RPushbullet](https://cran.r-project.org/package=RPushbullet): R Interface to the Pushbullet Messaging Service (ACCOUNT REQUIRED)
* [x] [ntfy](https://github.com/jonocarroll/ntfy) (R package): [ntfy](https://ntfy.sh/) (pronounce: notify) is a simple HTTP-based [pub-sub](https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern) notification service. It allows you to send notifications to your phone or desktop via scripts from any computer, entirely without signup, cost or setup. It's also [open source](https://github.com/binwiederhier/ntfy) if you want to run your own.
* [ ] [keep](https://github.com/keephq/keep) - Alerting. By developers, for developers.
* [ ] [pushsafer](https://www.pushsafer.com/) - looks awesome.

# Messages / Channels

* [ ] [slackr](https://cran.r-project.org/package=slackr): Send Messages, Images, R Objects and Files to 'Slack' Channels/Users
* [ ] [streamR](https://cran.r-project.org/package=streamR): Access to Twitter Streaming API via R
* [ ] [telegram](https://cran.r-project.org/package=telegram): R Wrapper Around the Telegram Bot API
* [ ] [twitteR](https://cran.r-project.org/package=twitteR): R Based Twitter Client

# GUIs

* [x] RStudio Console
* [ ] VSCode, e.g. <https://code.visualstudio.com/updates/v1_22#_show-long-running-operations-as-notifications-with-cancellation-support>

# Miscellaneous

* [ ] [txtq](https://cran.r-project.org/package=txtq): A Small Message Queue for Parallel Processes
* [ ] [PingMe](https://pingme.lmno.pk/#/services) - supports many of the above message services  (Discord, Email, Gotify, Line, Mastodon, Mattermost, Microsoft Teams, Pushbullet, Pushover, RocketChat, Slack, Telegram, Textmagic, Twillio, Zulip, and Wechat)
* [ ] [UnifiedPush](https://unifiedpush.org/): a set of specifications and tools that lets the user choose how push notifications* are delivered. All in a free and open source way.
